"""Write benchmark/presets/presets_by_scene.json: presets keyed by the scene name in use.

Why this is needed. presets.json is keyed by the path each scene had when its presets were
exported, which is the asset's original name:

    scenes/postwar-city-exterior-scene/d77c0cc629164202b994da7e203115fc.blend

The benchmark CSV and the download layout use a normalised name for the same scene:

    scenes/postwar-city/postwar-city.blend

Nothing can turn one into the other by string manipulation, so on a fresh clone there is no
programmatic answer to "which presets belong to this scene". Anything that needs to work per
scene, such as pre-capturing panoramas or indexing them, has to guess.

The mapping is recoverable, because preset names are unique across scenes: match each entry in
presets.json to the scene whose CSV rows use those preset names. That is done once, here, and
written down, so that consumers read a fact instead of repeating an inference.

    python3 scripts/build_preset_index.py

Re-run after adding a scene or renaming a preset.
"""
import collections
import csv
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRESETS = ROOT / "benchmark" / "presets" / "presets.json"
CSV_PATH = Path(os.environ.get("SCOPE_CSV", ROOT / "benchmark" / "scope_536.csv"))
OUT = ROOT / "benchmark" / "presets" / "presets_by_scene.json"


def main():
    pj = json.loads(PRESETS.read_text())

    used = collections.defaultdict(set)
    paths = {}
    for row in csv.DictReader(CSV_PATH.open(newline="")):
        loc = row.get("file_location") or ""
        parts = loc.split("/")
        if len(parts) < 2:
            continue
        scene = parts[1]
        paths[scene] = loc
        p = (row.get("preset_start") or "").strip()
        if p:
            used[scene].add(p)

    out, unmatched = {}, []
    for orig, presets in pj.items():
        names = set(presets)
        best, score = None, 0
        for scene, want in used.items():
            n = len(names & want)
            if n > score:
                best, score = scene, n
        if not best:
            unmatched.append(orig)
            continue
        out[best] = {
            "scene": best,
            "file_location": paths[best],
            "original_blend": orig,
            "presets": {
                name: {
                    "location": data.get("location"),
                    "rotation_euler": data.get("rotation_euler"),
                    "rotation_mode": data.get("rotation_mode", "XYZ"),
                    "lens": data.get("lens"),
                    "type": data.get("type", "PERSP"),
                    "clip_start": data.get("clip_start"),
                    "clip_end": data.get("clip_end"),
                    "used_by_rows": name in used[best],
                }
                for name, data in presets.items()
            },
        }

    doc = {
        "_comment": [
            "Camera presets keyed by the scene name the benchmark uses, generated by",
            "scripts/build_preset_index.py from presets.json and the benchmark CSV.",
            "",
            "presets.json is keyed by each scene's original asset filename, which does not",
            "match the name the CSV and the download layout use and cannot be derived from it.",
            "This file records the correspondence so that tools do not have to infer it.",
            "",
            "Rotations are radians, XYZ Euler. Lens is millimetres. These are the same numbers",
            "the installed .py presets assign, so a pose here is exactly what applying the",
            "preset produces.",
        ],
        "scenes": out,
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    for scene, e in sorted(out.items()):
        used_n = sum(1 for p in e["presets"].values() if p["used_by_rows"])
        print(f"  {scene:14} {len(e['presets'])} presets ({used_n} used by rows)  "
              f"<- {e['original_blend']}")
    for u in unmatched:
        print(f"  UNMATCHED {u}: no CSV rows use any of its presets")


main()
